version: '3.8'

services:
  app:
    image: sanjaykshebbar/finance-board-v2:latest
    container_name: finance-board-app-prod
    ports:
      - "8081:80"
    volumes:
      - ./db:/var/www/html/db
      - ./uploads:/var/www/html/uploads
    restart: always
